apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: miqio-proxy

generatorOptions:
  disableNameSuffixHash: true

resources:
  - deployment.yaml
  - secrets.yaml
  - regcred-secret.yaml
  - mounted-secrets.yaml
